name: loupgaroutest12
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.1
  firebase_auth: ^0.18.2
  settings_ui: ^0.5.0
  clipboard_manager: ^0.0.4
  page_transition: ^1.1.7+2
  animated_splash_screen: ^1.0.1+2
  flutter_spinkit: ^4.1.2+1
  lottie: ^0.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/settings-icon.png
    - assets/images/comd.jpg
    - assets/images/voleur.png
    - assets/images/loupN.png
    - assets/images/Pfille.png
    - assets/images/necro.png
    - assets/images/LoupB.png
    - assets/images/BEM.png
    - assets/images/ASec.png
    - assets/images/background-loup.jpg
    - assets/images/wolf-silhouette-detailed-tattoo.png
    - assets/images/alien.jpg
    - assets/images/Ancien.jpg
    - assets/images/Sorcière.jpg
    - assets/images/voyante.jpg
    - assets/images/ange.jpg
    - assets/images/barbier.jpg
    - assets/images/capitaine.jpg
    - assets/images/Chasseur.jpg
    - assets/images/Chevalier.jpg
    - assets/images/Chien-Loup.png
    - assets/images/Corbeau.jpg
    - assets/images/cupidon.jpg
    - assets/images/enfant sauvage.jpg
    - assets/images/frere.jpg
    - assets/images/Grand Méchant Loup.jpg
    - assets/images/idiot.jpg
    - assets/images/Infecte pere.jpg
    - assets/images/Joueur de Flute.jpg
    - assets/images/juge.jpg
    - assets/images/Ours.jpg
    - assets/images/pyro.jpg
    - assets/images/Renard.jpg
    - assets/images/servante.jpg
    - assets/images/soeur.jpg
    - assets/images/Loup-Garou.jpg
    - assets/images/sv.jpg
    - assets/images/salva.jpg
    - assets/images/night.jpg
    - assets/images/nightwolf.jpg
    - assets/images/house.jpg
    - assets/Lottie/34605-lonely-wolf.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Cinzel
     fonts:
       - asset: fonts/Cinzel-VariableFont_wght.ttf

   - family: Montserrat
     fonts:
       - asset: fonts/Montserrat-Light.ttf

#
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
